[package]
name = "bridge-lockbox"
version = "0.1.0"

[lib]
kind = "account-component"
namespace = "miden:bridge-lockbox/bridge-lockbox@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"

[package.metadata.miden]
supported-types = ["RegularAccountImmutableCode"]
