[package]
name = "amm-pool"
version = "0.1.0"

[lib]
kind = "account-component"
namespace = "miden:amm-pool/amm-contract@0.1.0"

[dependencies]
miden-core = "*"
miden-protocol = "*"

[package.metadata.miden]
supported-types = ["RegularAccountUpdatableCode"]