[workspace]
members = [
    "integration"
, "contracts/bank-account", "contracts/deposit-note", "contracts/withdraw-note", "contracts/ballot-box", "contracts/vote-note", "contracts/time-lock-vault", "contracts/vault-deposit-note", "contracts/vault-withdraw-note"]
exclude = [
    "contracts/",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
